### ISSUE TITLE
Questions on operation

### ISSUE THREAD

**Issue by lf94** [MarkWheadon/velocity-painting#25]
Hey,

Does velocity-painting work on G2/G3 and G5 codes? I presume no, because of the explicit mention of "GCODE vector".

What is a "GCODE vector" ? Is it the line that forms between two G1s? Or just G1s line from the origin?

**Comment by MarkWheadon** [comment]
Hi Lee – it's been a long while since I last looked at the code, but no –
it doesn't know about anything fancy like arcs / circles / that kind of
thing. The GCODE I wrote it for only had linear moves – and it chops up the
linear moves into segments small enough to allow fine detail in the
painting.

Cheers,

Mark

**Comment by lf94** [comment]
Thank you - yes, this is what I had come to the conclusion of after looking at it very closely. On paper it wouldn't be much more difficult to include G2/G3, but I've learned that essentially no slicers support those codes anyway (for a variety of reasons).

I have a plan devised to indicate where to slow/speed up the print head, but it involves using volumetric modelers.
