### ISSUE TITLE
example settings for S3D

### ISSUE THREAD

**Issue by ghost** [MarkWheadon/velocity-painting#5]
i think it would be practical for users, if you could add a sample S3D settings or .factory file to the example outputs. It would be alot easier to follow up on your instructions.

Thanks in advance.

**Comment by MarkWheadon** [comment]
Sure -- will do.

**Comment by ghost** [comment]
That´s great. i have tried several times now but I don´t seem to get any output on my gcodes. I make them with S3D and then I send them through the script. Are there more variables to set besides speeds?

**Comment by MarkWheadon** [comment]
Send me a smallish gcode and image and I'll be happy to take a quick look. Either attach them to this thread or email me at mark.wheadon at the usual gmail domain.

**Comment by ghost** [comment]
Okay, here are the zipped files. I sliced everything to 7200 mm/min and undersped them to 50%. You can´t set the speed settings to zero. Then I sent the gcode file through the script with xwidth ywidth set to 50mm.
The only thing happening is that the whole object gets slowed down.
[velocity-painting.zip](https://github.com/MarkWheadon/velocity-painting/files/793448/velocity-painting.zip)
 EDIT: i just saw, that I edited the wrong lines. However, it´s the same when editing the right ones.

**Comment by MarkWheadon** [comment]
Ah, OK, so one problem will be with the under-speed. That's a %age of full speed but actually refers to the _speed_ not the _under_speed (in spite of the name :-) -- so it needs to be set to 100%. That wouldn't cause a complete failure of image mapping though so I'll investigate.

**Comment by MarkWheadon** [comment]
Got it. The problem is one I have addressed in the push to Github I did last night. My models usually sit at (0,0) on the bed, because my printer is a delta. Yours looks to have a 250x250mm bed with the origin being at the front left corner so the middle is at (125,125) -- so the image and the model weren't overlapping.

If you pull the latest version ("git pull origin master" I think, but I'm new to git) and run it as follows you should get the following GCODE. There are still some high-speed stripes in the GCODE which are much faster than 2700 (your Simplify3D settings need tweaking), so it mostly works but has high-speed (3600mm/min, so 60mm/s) stripes on the side and back.

./velPaint -projectX 125 125 40 - 6 7200 800 2500 stg.jpg testcube.gcode > testcubepainted.gcode

GCODE: https://www.dropbox.com/s/8t4ef8njc7cug4d/testcubepainted.gcode?dl=0

Running velPaint with no parameters explains the above:

Usage:
  ./velPaint -projectX  printCentreX printCentreY imageWidth imageHeight zOffset targetSpeed lowSpeed highSpeed imageFile [sourceGcodeFile] > paintedGcodeFile
  ./velPaint -cylinderZ printCentreX printCentreY            imageHeight zOffset targetSpeed lowSpeed highSpeed imageFile [sourceGcodeFile] > paintedGcodeFile

printCentre{X,Y} is the centre of the print in the printer's coordinate space, in mm.
When the print in centred on the bed then printCentre{X,Y} is 0,0 for most (all?) detas. 125,125 for the Prusa i3 MK2.
imageWidth and imageHeight are also in mm.
Specifying an imageWith of '-' sets it to the correct width for the specified height.
Specifying an imageHeight of '-' sets it to the correct height for the specified width.
targetSpeed is the speed of the vectors you wish to manipulate
(so slice the model with all speeds set to this value).
lowSpeed is the required speed for the slow parts of the print
highSpeed is the required speed for the quick parts of the print
imageFile is the image to be mapped onto the print.

All speeds above are in mm/min.

**Comment by ghost** [comment]
Well done! i could have figured that out by myself. the script is working now, so there is a clear confirmation for Archlinux. I also had to change the folder where the perl binary lives in linux it´s /usr/bin/perl.

The picture gets mapped straight through the object right?

**Comment by MarkWheadon** [comment]
Yes that's right, and yes /usr/bin/perl is the sensible place for it. In my case I have more than one version of perl installed and didn't want to mess with the default perl, hence the strange path.

**Comment by ghost** [comment]
Okay great. Here is the result of the above. i will play around for little now.

![img_20170223_072105](https://cloud.githubusercontent.com/assets/15875927/23247677/b4231b6c-f99b-11e6-87ac-10083b81d293.jpg)
![img_20170223_072131](https://cloud.githubusercontent.com/assets/15875927/23247678/b426170e-f99b-11e6-9c36-5931df54d120.jpg)
